### ISSUE TITLE
[Suggestion] Hopefully it will be compatible with folia

### ISSUE THREAD

**Issue by HYDeath** [magemonkeystudio/genesis#30]
Wish I could get bossshoppro to support compatibility on folia, just a simple adaptation would be nice.
Documentation for folia: https://docs.papermc.io/folia

**Comment by Travja** [comment]
Since Folia is a fork of Paper, at the very base level, it should be compatible. Have you tried it out at all?

**Comment by HYDeath** [comment]
> Since Folia is a fork of Paper, at the very base level, it should be compatible. Have you tried it out at all?

I tried putting it in, but he reports an error, the error log is below:
https://paste.ubuntu.com/p/9vC5vPdMkx/
