### ISSUE TITLE
error when changing items language

### ISSUE THREAD

**Issue by frogglen** [magemonkeystudio/genesis#37]
https://github.com/ColorsWind/LanguageUtils

I am using the latest version of BossShopPro, I installed the library to change the language of the items, but it doesn't seem to work, the items are still in English.

**Comment by goflishMC** [comment]
> https://github.com/ColorsWind/LanguageUtils
> 
> I am using the latest version of BossShopPro, I installed the library to change the language of the items, but it doesn't seem to work, the items are still in English.

colorsWind is not our plugin, so not sure what you are trying to do

**Comment by frogglen** [comment]
> > https://github.com/ColorsWind/LanguageUtils
> > I am using the latest version of BossShopPro, I installed the library to change the language of the items, but it doesn't seem to work, the items are still in English.
> 
> colorsWind is not our plugin, so not sure what you are trying to do

I want the items to appear in Spanish, how can I do it, I thought I had to install the library?

**Comment by frogglen** [comment]
hello?

**Comment by Travja** [comment]
I'm not sure how that utility is supposed to work or how you'd expect it to work with BSP.

**Comment by frogglen** [comment]
![image](https://github.com/promcteam/BossShopPro/assets/6269642/79de06b2-cc47-492b-9e30-88a3618cbde3)

instead of saying coal, it is supposed to be automatically translated into the language of my client or the one I want by default.

> I'm not sure how that utility is supposed to work or how you'd expect it to work with BSP.

**Comment by Travja** [comment]
Is this plugin supposedly supposed to work well with BSP?

**Comment by frogglen** [comment]
> Is this plugin supposedly supposed to work well with BSP?

this text appears in the language text:

```
#You can make BossShopPro translate every enchantment and item into any language included in Vanilla minecraft.
#Optional & requires LangUtils to be installed (https://www.spigotmc.org/resources/1-10-x-1-9-x-1-8-x-1-7-10-language-utils.8859/)
#Here you can find a list of locale ids: http://www.oracle.com/technetwork/java/javase/javase7locales-334809.html
Locale: en_us
```

if I change it to es_mx or es_es it doesn't seem to work and nothing is translated, try to install the plugin that comes in that message and it doesn't work either.

**Comment by Travja** [comment]
Closing this as it has been without discussion for over a year and our efforts to provide a solution have been a bit hap-hazard and probably more work than it's worth. If, at some point, Maksy wants to revisit this, that's up to them, but I don't see a need to keep the ticket open.
