### ISSUE TITLE
[Suggestion] Shulker Box Support

### ISSUE THREAD

**Issue by CupOHappiness** [magemonkeystudio/genesis#44]
I couldn't find a way to do it. Trying to add a Shulker Box with items to a shop.

**Comment by MaksyKun** [comment]
Im not sure if this is good practice to add shulkerboxes with content in BossShoppro since you always create one MenuItem for a slot. Do you aim for a possibility of buying more than one Item-type in general?

**Comment by Travja** [comment]
I don't really feel like this is a good candidate for Genesis. If you're trying to sell multiple items at once, I would recommend some sort of kit plugin that you can just execute the `/kit give` command as the console and give the player the kit upon purchase.
