### ISSUE TITLE
"/bs" no longer working after update to Genesis 1.0.0

### ISSUE THREAD

**Issue by MarvinKlar** [magemonkeystudio/genesis#70]
I just updated from bossshoppro-2.1.0-R0.9-20240307.151018-1.jar to genesis-1.0.0-R0.4-20240601.183146-1.jar and nothing is working on my server. All /bs commands in all possible configs are no longer working. Yould you please add the command /bs as an alias again?!

**Comment by Travja** [comment]
The `bs` alias was removed and all references to `BossShop` and related names have been changed to `Genesis`. Though we're a continuation of BSP itself, we've rebranded and those commands will not work anymore.
