### ISSUE TITLE
Bug Report: Genesis Plugin Custom Skull Item Creation Error

### ISSUE THREAD

**Issue by var1nthon** [magemonkeystudio/genesis#81]
**Description of the Bug**
The Genesis plugin encounters an error when attempting to create a custom skull item in the shop. The specific issue is that the profile name for the custom skull exceeds the maximum allowed length of 16 characters, causing an IllegalArgumentException. This results in the plugin failing to create the item and suggesting that the issue is likely due to configuration mistakes.

**Steps to Reproduce**
Configure a shop in the Genesis plugin that includes a custom skull item.
Ensure the profile name for the custom skull exceeds 16 characters.
Start the server and observe the error in the logs.

**Expected Behavior**
The Genesis plugin should handle the creation of custom skull items without exceeding the profile name length constraint or provide a more user-friendly error message indicating the exact problem.

**Actual Behavior**
The plugin throws an IllegalArgumentException and fails to create the custom skull item due to the profile name exceeding 16 characters.

**Suggested Fix**
Ensure that all profile names for custom skulls in the shop configuration are 16 characters or fewer. Additionally, the plugin could be improved to validate the length of profile names before attempting to create the item, providing a clear error message if the constraint is violated.

**Version Info**
Genesis: 1.0.0-R0.4-SNAPSHOT
Paper: This server is running Paper version 1.21-54-master@f250ec0 (2024-07-11T16:05:17Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 45 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-55-7bd22b1 (MC: 1.21)

**Additional context**
log: https://paste.denizenscript.com/View/124792
spark: https://spark.lucko.me/tJAC5yLAID

**Comment by Travja** [comment]
You're using the base-64 encoded texture string for the skulls, correct? Could you send an example?

**Comment by Travja** [comment]
Could you also try grabbing a newer build from our Discord and see if you still have issues?
