### ISSUE TITLE
[Suggestion] Create a new currency using fly time (TempFly)

### ISSUE THREAD

**Issue by Njordyr** [magemonkeystudio/genesis#87]
Hey, I'm after an addition that allows you to use a players fly time as currency in the shop, for example you can use 30 seconds of fly time to buy an item. The values would only be in seconds so 1 would be one second of fly time.
It would be hooked from this plugin https://www.spigotmc.org/resources/tempfly-now-includes-factions-fly.54987/

**Comment by Travja** [comment]
This is definitely more in the realm of a Genesis Addon and not a project I think belongs in main-stream Genesis.
