### ISSUE TITLE
genesis GUI bug

### ISSUE THREAD

**Issue by LinAk900127** [magemonkeystudio/genesis#95]
Paper Server :1.21.1
genesis-1.0.1-R0.4-20241006.023017-1
----------------------------------------------
When the shop menu is open, point the mouse at any item and press F to alternately hold the object. You can hold the object in your hand.
I think this is a serious bug
Supplement: In fact, this problem already existed several versions ago!
It doesn’t only exist in 1.21
![image](https://github.com/user-attachments/assets/155d0bec-55cd-478f-92e4-0fa7481ea13a)
![image](https://github.com/user-attachments/assets/8f5a80b6-43c3-4f36-af52-4e40c30e242c)
![image](https://github.com/user-attachments/assets/dec7a8c2-89f6-44a1-9b00-cb1b3725a9b2)

**Comment by Travja** [comment]
It looks like this is only a visual bug and the item isn't actually in your hand. If you click on it, it goes away.
