### ISSUE TITLE
Colorcode not recognized in Genesis lore

### ISSUE THREAD

**Issue by Blackarr** [magemonkeystudio/genesis#98]
So if you use some placeholder Genesis ignores the color code in the placeholder output.

     - 'lore:%checkitem_getinfo:mainhand_lorecontains:0%'
    - 'lore:%changeoutput_match_input:{player_has_permission_handwerk.heizen.amboss}_matcher:yes_ifmatch:&81_else:&c2%'

Genesis lore output wrong:
![image](https://github.com/user-attachments/assets/c370e84e-ea73-40e3-bc23-bc5323f13bb6)

the second Placeholder output should be &c2 (a red "2"). i tested it outside of Genesis and it works just as intended.

Example where it works:
![image](https://github.com/user-attachments/assets/d3e8b6fb-7ecc-492c-b1e1-ea2d06bfb0d4)

  tested in: genesis-1.0.0-R0.4-20240601.183146-1

**Comment by Blackarr** [comment]
%changeoutput is a expansion from PAPI able of logic if else
with it i wanted to check for player permission and have diffrent lore outputs and use "ExtraPermission: " to effektivly have one shop instead of three and because i need to recreate this multipletimes i would be saving 100 shops.
%checkitem is also a expansion it is giving out the first loreline of a item but working just fine and as intended.
I already tried it with "§" but it is getting ignored just like "&".
I tested the Placeholder it works but just Genesis has problem with the colors somehow.

**Comment by Travja** [comment]
There is a new build on Discord now that should work for you

**Comment by Blackarr** [comment]
thank you <3

**Comment by Blackarr** [comment]
hey sorry Travja where can i find the new devbuild on Discord? cant seem to find it
